### ISSUE TITLE
Display the correct message when a branch gets deleted

### ISSUE THREAD

**Issue by dfyx** [spruce/hubot-gitlab-hooks#7]
Currently, it reports something like the following:

> DFYX pushed 0 commits to feature/some-feature in some-project (http://gitlab.example.com/namespace/some-projects/compare/d6d308cbc...000000000)

Expected behavior would be:

> DFYX deleted branch feature/some-feature in some-project

**Comment by spruce** [comment]
Hey,
thanks for the report. Gonna look into it in the next week.

**Comment by spruce** [comment]
Which version are you on? Because I get the correct message.

**Comment by dfyx** [comment]
Sorry, I used the version that comes with hubot-scripts. Just switched to the current master (plus #11) and now it works.
