### ISSUE TITLE
Better messages for merge requests

### ISSUE THREAD

**Issue by dfyx** [spruce/hubot-gitlab-hooks#8]
Currently, all events (create, merge, close, edit, amend) on merge requests generate the same message format and it's really hard to see what actually happened. Also there's no link to the merge request itself.

I would prefer something like the following:

Create:
> DFYX **created** Merge Request #42 "Lorem ipsum dolor" in some-project (http://gitlab.example.com/namespace/someproject/merge_requests/42)
>> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

Merge:
> DFYX **merged** Merge Request #42 "Lorem ipsum dolor" in some-project (http://gitlab.example.com/namespace/someproject/merge_requests/42)

Close:
> DFYX **closed** Merge Request #42 "Lorem ipsum dolor" in some-project (http://gitlab.example.com/namespace/someproject/merge_requests/42)

Edit:
> DFYX **edited** Merge Request #42 "Lorem ipsum dolor" in some-project (http://gitlab.example.com/namespace/someproject/merge_requests/42)

Amend:
> DFYX **added 2 new commits** to Merge Request #42 "Lorem ipsum dolor" in some-project (http://gitlab.example.com/namespace/someproject/merge_requests/42)

**Comment by spruce** [comment]
Problem is. We don't get that much information from gitlab. at least as I see it:
```
{"object_kind":"merge_request","object_attributes":
  {"id":2,"target_branch":"master","source_branch":"develop",
  "source_project_id":1,"author_id":3,"assignee_id":3,"title":"Develop",
  "created_at":"2015-06-07 14:21:40 UTC","updated_at":"2015-06-07 14:24:14 UTC",
  "milestone_id":26,"state":"reopened","merge_status":"unchecked",
  "target_project_id":1,"iid":2,"description":"mergerdesc\r\n\r\nmore desc","position":0
  }
}
```

**Comment by dfyx** [comment]
Still some problems:

> Merge Request 1: dfyx opened Add gitlab.coffee (opened) between somebranch and master

As you can see, "opened" appears twice.

**Comment by spruce** [comment]
Right. One is the state of the MR and the other is the action performed. 

But I think you are right. will remove the one in parenthesis

**Comment by dfyx** [comment]
I'd say it's purely cosmetic so you don't need to hurry.
